export const safetyMenu = [
  {
    id: `How Your OneCard Keeps You Safe from Credit card Fraud`,
    imageLink: `https://www.getonecard.app/images/blog/blog_stay_safe_with_onecard.png`,
    Date: `Dec 13, 2021`,
    query: `How Your OneCard Keeps You Safe from Credit card Fraud`,
  },
  {
    id: `Credit Card Skimming -What is It and How to Avoid It?`,
    imageLink: `https://www.getonecard.app/images/blog/blog_credit_card_skimming.png`,
    Date: `Nov 24, 2021`,
    query: `Credit Card Skimming -What is It and How to Avoid It?`,
  },
  {
    id: `How to avoid fraud via screen sharing apps`,
    imageLink: `https://www.getonecard.app/images/blog/blog_fraud_screen_mirroring.png`,
    Date: `Oct 14, 2021`,
    query: `How to avoid fraud via screen sharing apps`,
  },
  {
    id: `Tap In-App' to Authenticate Your Online Transaction`,
    imageLink: `https://www.getonecard.app/images/blog/blog_tap_in_app.png`,
    Date: `Oct 11, 2021`,
    query: `Tap In-App' to Authenticate Your Online Transaction`,
  },
];

export const RepaymentsAndEmi = [
  {
    id: `OneCard Credit Card Statement: A Complete Guide`,
    imageLink: `https://www.getonecard.app/images/blog/Understanding_OneCard_Statement.jpg`,
    date: `Jun 21, 2021`,
    query: `OneCard Credit Card Statement: A Complete Guide`,
  },
  {
    id: `Mithai, Masti, Holi... and Bonus Points!`,
    imageLink: `https://www.getonecard.app/images/blog/blog_onecard_sweet_fest.png`,
    date: `Mar 27, 2021`,
    query: `Mithai, Masti, Holi... and Bonus Points!`,
  },
  {
    id: `Understand OneCard Credit Card Bill Repayment`,
    imageLink: `https://www.getonecard.app/images/blog/blog_making_onecard_repayment.jpg`,
    date: `Feb 16, 2021`,
    query: `Understand OneCard Credit Card Bill Repayment`,
  },
  {
    id: `Understanding & Avoiding OneCard Credit Card Interest Charges`,
    imageLink: `https://www.getonecard.app/images/blog/blog_interest_charges_onecard.jpg`,
    date: `Feb 03, 2021`,
    query: `Understanding & Avoiding OneCard Credit Card Interest Charges`,
  },
];

export const oneCardFeatures = [
  {
    id: `Best Gift Cards from Favourite Brands`,
    imageLink: `https://www.getonecard.app/images/blog/buy_giftcards_on_onestore.png`,
    date: `Jul 18, 2023`,
    query: `Best Gift Cards from Favourite Brands`,
  },
  {
    id: `Keep Track and Manage Your Expenses with OneCard App`,
    imageLink: `https://www.getonecard.app/images/blog/Stay_on_top_of_your_bills_with_OneCard.png`,
    date: `Feb 09, 2023`,
    query: `Keep Track and Manage Your Expenses with OneCard App`,
  },
  {
    id: `OneCard Fee Updates - Rent, Wallet Fee & Fuel Surcharge Waiver Cap`,
    imageLink: `https://www.getonecard.app/images/blog/Rent_Surcharge_Blog_.png`,
    date: `Feb 03, 2023`,
    query: `OneCard Fee Updates - Rent, Wallet Fee & Fuel Surcharge Waiver Cap`,
  },
  {
    id: ``,
    imageLink: `https://www.getonecard.app/images/blog/In_need_of_cash_Ask_OneCash.png`,
    date: `Jan 25, 2023`,
    query: `Get OneCash Instant Cash in 30 Seconds - OneCard`,
  },
  {
    id: `Introducing My Rent, all in one dashboard to manage and track rent payments.`,
    imageLink: `https://www.getonecard.app/images/blog/rent_pay_blog_.png`,
    date: `Sep 02, 2022`,
    query: `Introducing My Rent, all in one dashboard to manage and track rent payments.`,
  },
  {
    id: `How to Avoid Credit Card Late Payment Charges?`,
    imageLink: `https://www.getonecard.app/images/blog/A-Z_of_late_payment_fees.png`,
    date: `Aug 29, 2022`,
    query: `How to Avoid Credit Card Late Payment Charges?`,
  },
  {
    id: `MyFamily Feature - Get Your Family Their Own OneCard`,
    imageLink: `https://www.getonecard.app/images/blog/Share_your_limit_with_family%21.png`,
    date: `Jun 09, 2022`,
    query: `MyFamily Feature - Get Your Family Their Own OneCard`,
  },
  {
    id: `Why Create Fixed Deposit (FD) to Get OneCard Credit Card?`,
    imageLink: `https://www.getonecard.app/images/blog/blog_why_fd_.png`,
    date: `Nov 18, 2021`,
    query: `Why Create Fixed Deposit (FD) to Get OneCard Credit Card?`,
  },
  {
    id: ``,
    imageLink: `https://www.getonecard.app/images/blog/blog_tap_in_app.png`,
    date: `Oct 11, 2021`,
    query: `Tap In-App' to Authenticate Your Online Transaction`,
  },
  {
    id: `Understanding OneCard Rewards Programme`,
    imageLink: `https://www.getonecard.app/images/blog/Understanding_OneCard_Rewards.png`,
    date: `Sep 22, 2021`,
    query: `Understanding OneCard Rewards Programme`,
  },
  {
    id: `Goodbye OTPs, Swipe to Pay is Here for Payment!`,
    imageLink: `https://www.getonecard.app/images/blog/blog_swipe_to_pay.jpg`,
    date: `Jul 08, 2021`,
    query: `Goodbye OTPs, Swipe to Pay is Here for Payment!`,
  },
  {
    id: `OneCard Credit Card Statement: A Complete Guide`,
    imageLink: `https://www.getonecard.app/images/blog/Understanding_OneCard_Statement.jpg`,
    date: `Jun 21, 2021`,
    query: `OneCard Credit Card Statement: A Complete Guide`,
  },
  {
    id: `A Faster Way to Get Your OneCard Credit Card`,
    imageLink: `https://www.getonecard.app/images/blog/blog_get_onecard_faster.png`,
    date: `Apr 12, 2021`,
    query: `A Faster Way to Get Your OneCard Credit Card`,
  },
  {
    id: `Mithai, Masti, Holi... and Bonus Points!`,
    imageLink: `https://www.getonecard.app/images/blog/blog_onecard_sweet_fest.png`,
    date: `Mar 27, 2021`,
    query: `Mithai, Masti, Holi... and Bonus Points!`,
  },
  {
    id: `OneCard Credit Card EMI - What is It and How Does It Work?`,
    imageLink: `https://www.getonecard.app/images/blog/blog_introducing_onecard_emi.png`,
    date: `Mar 23, 2021`,
    query: `OneCard Credit Card EMI - What is It and How Does It Work?`,
  },
  {
    id: `Understand OneCard Credit Card Bill Repayment`,
    imageLink: `https://www.getonecard.app/images/blog/blog_making_onecard_repayment.jpg`,
    date: `Feb 16, 2021`,
    query: `Understand OneCard Credit Card Bill Repayment`,
  },
  {
    id: `Understanding & Avoiding OneCard Credit Card Interest Charges`,
    imageLink: `https://www.getonecard.app/images/blog/blog_interest_charges_onecard.jpg`,
    date: `Feb 03, 2021`,
    query: `Understanding & Avoiding OneCard Credit Card Interest Charges`,
  },
  {
    id: `Christmas Bonanza by the numbers`,
    imageLink: `https://www.getonecard.app/images/blog/blog_onecard_xmas_bonanza_stats.jpg`,
    date: `Jan 20, 2021`,
    query: `Christmas Bonanza by the numbers`,
  },
  {
    id: `OneCard Christmas Bonanza is here`,
    imageLink: `https://www.getonecard.app/images/blog/blog_onecard_christmas_bonanza.jpg`,
    date: `Dec 24, 2020`,
    query: `OneCard Christmas Bonanza is here`,
  },
  {
    id: `Light up Diwali with OneCard Bonanza`,
    imageLink: `https://www.getonecard.app/images/blog/blog_diwali_bonanza2020.png`,
    date: `Nov 12, 2020`,
    query: `Light up Diwali with OneCard Bonanza`,
  },
  {
    id: `No Waitlist! Get OneCard Now`,
    imageLink: `https://www.getonecard.app/images/blog/OneCard_On_Tap.jpg`,
    date: `Oct 13, 2020`,
    query: `No Waitlist! Get OneCard Now`,
  },
  {
    id: `The OneCard Waitlist 2.0 Explained`,
    imageLink: `https://www.getonecard.app/images/blog/OneCard_Waitlist2.jpg`,
    date: `Aug 20, 2020`,
    query: `The OneCard Waitlist 2.0 Explained`,
  },
  {
    id: `OneCard 5x Rewards Update 2023`,
    imageLink: `https://www.getonecard.app/images/blog/Blog_OneRewards_June2020.jpg`,
    date: `Jul 17, 2020`,
    query: `OneCard 5x Rewards Update 2023`,
  },
  {
    id: `OneCard is ready to rock n' roll`,
    imageLink: `https://www.getonecard.app/images/blog/OneCard_rocknroll.png`,
    date: `Jun 02, 2020`,
    query: `OneCard is ready to rock n' roll`,
  },
  {
    id: `Closer to Getting OneCard`,
    imageLink: `https://www.getonecard.app/images/blog/OneCard_AStepCloser.png`,
    date: `Mar 20, 2020`,
    query: `Closer to Getting OneCard`,
  },
  {
    id: `Introducing OneCard: Tips to Get It and Waitlist Key Features`,
    imageLink: `https://www.getonecard.app/images/blog/Introducing_OneCard.png`,
    date: `Feb 11, 2020`,
    query: `Introducing OneCard: Tips to Get It and Waitlist Key Features`,
  },
];

export const cultureAndCreditCard = [
  {
    id: `Things to Consider While Buying Gold During Festive Season`,
    imageLink: `https://www.getonecard.app/images/blog/buying_gold.png`,
    date: `Nov 08, 2023`,
    query: `Things to Consider While Buying Gold During Festive Season`,
  },
  {
    id: `OneCard Metal Credit Card - Make Heads Turn`,
    imageLink: `https://www.getonecard.app/images/blog/classNamey_metal.png`,
    date: `Oct 30, 2023`,
    query: `OneCard Metal Credit Card - Make Heads Turn`,
  },
  {
    id: `Tips for Buying Electronic Gadgets During Festive Sales`,
    imageLink: `https://www.getonecard.app/images/blog/Shopping_Electronics.png`,
    date: `Oct 30, 2023`,
    query: `Tips for Buying Electronic Gadgets During Festive Sales`,
  },
  {
    id: `Get The Best Deals During Online Festive Sales`,
    imageLink: `https://www.getonecard.app/images/blog/festive_sale_shopping_tips_1.png`,
    date: `Oct 05, 2023`,
    query: `Get The Best Deals During Online Festive Sales`,
  },
  {
    id: `Tips for Managing Work Expenses with Your OneCard`,
    imageLink: `https://www.getonecard.app/images/blog/work_related_expense_management.png`,
    date: `Oct 03, 2023`,
    query: `Tips for Managing Work Expenses with Your OneCard`,
  },
  {
    id: `How to Plan for Diwali Shopping`,
    imageLink: `https://www.getonecard.app/images/blog/diwali_shopping.png`,
    date: `Sep 26, 2023`,
    query: `How to Plan for Diwali Shopping`,
  },
  {
    id: `Experience Real India This Navratri and Dussehra`,
    imageLink: `https://www.getonecard.app/images/blog/best_places_to_see_dussehra_and_navratri_festival.png`,
    date: `Sep 25, 2023`,
    query: `Experience Real India This Navratri and Dussehra`,
  },
  {
    id: `Best Places for Solo Trip in India to Visit in November`,
    imageLink: `https://www.getonecard.app/images/blog/best_places_to_visit_for_a_solo_trip_in_november.png`,
    date: `Sep 21, 2023`,
    query: `Best Places for Solo Trip in India to Visit in November`,
  },
  {
    id: `Ideas for a Week Long Vacation In October`,
    imageLink: `https://www.getonecard.app/images/blog/best_places_to_visit_in_october_in_india.png`,
    date: `Aug 22, 2023`,
    query: `Ideas for a Week Long Vacation In October`,
  },
  {
    id: `Unique Raksha Bandhan Gift Ideas for Sisters`,
    imageLink: `https://www.getonecard.app/images/blog/gift_ideas_for_raksha_bandhan.png`,
    date: `Aug 18, 2023`,
    query: `Unique Raksha Bandhan Gift Ideas for Sisters`,
  },
  {
    id: `Why Get Add On Credit Cards For Your Family`,
    imageLink: `https://www.getonecard.app/images/blog/why_get_add_on_credit_cards_for_your_family1.png`,
    date: `Aug 14, 2023`,
    query: `Why Get Add On Credit Cards For Your Family`,
  },
  {
    id: `How To Manage Lifestyle Inflation`,
    imageLink: `https://www.getonecard.app/images/blog/how_to_manage_lifestlye_inflation.png`,
    date: `Aug 11, 2023`,
    query: `How To Manage Lifestyle Inflation`,
  },
  {
    id: `How to Become a Credit Card Power User`,
    imageLink: `https://www.getonecard.app/images/blog/secretsofcreditcarduser.png`,
    date: `Aug 08, 2023`,
    query: `How to Become a Credit Card Power User`,
  },
  {
    id: `How Can Credit Cards Improve Your Financial Health`,
    imageLink: `https://www.getonecard.app/images/blog/financialhealthcreditcardblogbanner.png`,
    date: `Jul 31, 2023`,
    query: `How Can Credit Cards Improve Your Financial Health`,
  },
  {
    id: `How To Manage Your Credit Card Bills Effectively`,
    imageLink: `https://www.getonecard.app/images/blog/keep_your_credit_card_bills_in_check.png`,
    date: `Jul 18, 2023`,
    query: `How To Manage Your Credit Card Bills Effectively`,
  },
  {
    id: `Should You Increase Your Credit Card Limit`,
    imageLink: `https://www.getonecard.app/images/blog/should_you_increase_your_credit_limit.png`,
    date: `Jul 07, 2023`,
    query: `Should You Increase Your Credit Card Limit`,
  },
  {
    id: `​​5 Common Credit Card Myths Busted`,
    imageLink: `https://www.getonecard.app/images/blog/common_credit_card_myths_you_should_not_believe.png`,
    date: `Jun 28, 2023`,
    query: `​​5 Common Credit Card Myths Busted`,
  },
  {
    id: `Should You Keep Unused Credit Cards`,
    imageLink: `https://www.getonecard.app/images/blog/what_should_you_do_with_unused_credit_cards.png`,
    date: `Jun 28, 2023`,
    query: `Should You Keep Unused Credit Cards`,
  },
  {
    id: `​​6 Reasons Why Credit Cards Are Preferred for Online Shopping`,
    imageLink: `https://www.getonecard.app/images/blog/online_shopping_with_credit_cards.png`,
    date: `Jun 23, 2023`,
    query: `​​6 Reasons Why Credit Cards Are Preferred for Online Shopping`,
  },
  {
    id: `How to Redeem and Use Credit Card Reward Points?`,
    imageLink: `https://www.getonecard.app/images/blog/Tips_To_Redeem_Credit_Card_Rewards.png`,
    date: `Jun 14, 2023`,
    query: `How to Redeem and Use Credit Card Reward Points?`,
  },
  {
    id: `How Many Credit Cards Should You Have?`,
    imageLink: `https://www.getonecard.app/images/blog/5Reasonstogetanothercreditcard.png`,
    date: `May 05, 2023`,
    query: `How Many Credit Cards Should You Have?`,
  },
  {
    id: `How to Get The Most Out of Your Credit Card This Summer`,
    imageLink: `https://www.getonecard.app/images/blog/How_to_get_the_most_out_of_your_credit_card_this_summer_1200x628.png`,
    date: `May 03, 2023`,
    query: `How to Get The Most Out of Your Credit Card This Summer`,
  },
  {
    id: `8 Reasons Why You Should Get a Credit Card`,
    imageLink: `https://www.getonecard.app/images/blog/OC_8reasonswhyyoushouldgetacreditcard_BlogCreatives.png`,
    date: `Apr 02, 2023`,
    query: `8 Reasons Why You Should Get a Credit Card`,
  },
  {
    id: `How to Maximise Your Credit Card Reward Points`,
    imageLink: `https://www.getonecard.app/images/blog/The_secret_to_earning_more_reward_points.png`,
    date: `Mar 15, 2023`,
    query: `How to Maximise Your Credit Card Reward Points`,
  },
  {
    id: `Best Seasons to Use Credit Cards`,
    imageLink: `https://www.getonecard.app/images/blog/Bestseasonstousecreditcards.png`,
    date: `Jan 11, 2023`,
    query: `Best Seasons to Use Credit Cards`,
  },
  {
    id: `How to Pay Insurance Premium Through Credit Cards?`,
    imageLink: `https://www.getonecard.app/images/blog/Paying_premiums_with_credit_cards.png`,
    date: `Dec 22, 2022`,
    query: `How to Pay Insurance Premium Through Credit Cards?`,
  },
  {
    id: `5 Credit Card Myths That You Must Know`,
    imageLink: `https://www.getonecard.app/images/blog/3waystorelookatcreditcards.png`,
    date: `Nov 22, 2022`,
    query: `5 Credit Card Myths That You Must Know`,
  },
  {
    id: `5 Ways Credit Card Benefit You`,
    imageLink: `https://www.getonecard.app/images/blog/5specialwaysacreditcardcanhelpyou.png`,
    date: `Nov 07, 2022`,
    query: `5 Ways Credit Card Benefit You`,
  },
  {
    id: `4 Reasons Why Rich People Use Credit Cards`,
    imageLink: `https://www.getonecard.app/images/blog/Why_do_rich_people_need_credit_cards_27th%20june.png`,
    date: `Jun 29, 2022`,
    query: `4 Reasons Why Rich People Use Credit Cards`,
  },
  {
    id: `The Upside-Down of Credit Card Usage`,
    imageLink: `https://www.getonecard.app/images/blog/3_Real_Life_Unique_Uses_of_OneCard%20_1_new.png`,
    date: `Jun 20, 2022`,
    query: `The Upside-Down of Credit Card Usage`,
  },
  {
    id: `Debt Trap - What Is It and How to Avoid It?`,
    imageLink: `https://www.getonecard.app/images/blog/blog-avoid-debt-trap.png`,
    date: `Dec 29, 2021`,
    query: `Debt Trap - What Is It and How to Avoid It?`,
  },
  {
    id: `Do EMIs and BNPL Affect Your Credit Score?`,
    imageLink: `https://www.getonecard.app/images/blog/blog-emi-bnpl-affect-credit-score.png`,
    date: `Dec 20, 2021`,
    query: `Do EMIs and BNPL Affect Your Credit Score?`,
  },
  {
    id: `Mithai, Masti, Holi... and Bonus Points!`,
    imageLink: `https://www.getonecard.app/images/blog/blog_onecard_sweet_fest.png`,
    date: `Mar 27, 2021`,
    query: `Mithai, Masti, Holi... and Bonus Points!`,
  },
  {
    id: `Christmas Bonanza by the numbers`,
    imageLink: `https://www.getonecard.app/images/blog/blog_onecard_xmas_bonanza_stats.jpg`,
    date: `Jan 20, 2021`,
    query: `Christmas Bonanza by the numbers`,
  },
  {
    id: `OneCard Christmas Bonanza is here`,
    imageLink: `https://www.getonecard.app/images/blog/blog_onecard_christmas_bonanza.jpg`,
    date: `Dec 24, 2020`,
    query: `OneCard Christmas Bonanza is here`,
  },
];

export const creditCardInDepth = [
  {
    id: `Best Travel Credit Card in India`,
    imageLink: `https://www.getonecard.app/images/blog/travel_credit_cards.png`,
    date: `Nov 22, 2023`,
    query: `Best Travel Credit Card in India`,
  },
  {
    id: `Credit Card Flight Offers for Affordable and Rewarding Journeys`,
    imageLink: `https://www.getonecard.app/images/blog/flight_offers_on_credit_cards.png`,
    date: `Nov 22, 2023`,
    query: `Credit Card Flight Offers for Affordable and Rewarding Journeys`,
  },
  {
    id: `How to Close or Cancel Credit Card Online`,
    imageLink: `https://www.getonecard.app/images/blog/closing_your_credit_card.png`,
    date: `Nov 22, 2023`,
    query: `How to Close or Cancel Credit Card Online`,
  },
  {
    id: `How to Make UPI Payments Using Credit Card?`,
    imageLink: `https://www.getonecard.app/images/blog/pay_with_upi_using_credit_card.png`,
    date: `Nov 22, 2023`,
    query: `How to Make UPI Payments Using Credit Card?`,
  },
  {
    id: `Know How To Choose The Best Credit Card For Movie Tickets`,
    imageLink: `https://www.getonecard.app/images/blog/movie_ticket_offers_on_credit_cards.png`,
    date: `Nov 22, 2023`,
    query: `Know How To Choose The Best Credit Card For Movie Tickets`,
  },
  {
    id: `What Is a Credit Card and How Does It Work?`,
    imageLink: `https://www.getonecard.app/images/blog/all_about_credit_cards.png`,
    date: `Nov 22, 2023`,
    query: `What Is a Credit Card and How Does It Work?`,
  },
  {
    id: `Advantages and Disadvantages of Credit Cards in India`,
    imageLink: `https://www.getonecard.app/images/blog/advantages_of_using_credit_cards.png`,
    date: `Nov 15, 2023`,
    query: `Advantages and Disadvantages of Credit Cards in India`,
  },
  {
    id: `Fuel Surcharge Waiver on Credit Cards: What Is It and How Does It Work?`,
    imageLink: `https://www.getonecard.app/images/blog/fuel_surcharge_on_credit_cards.png`,
    date: `Nov 15, 2023`,
    query: `Fuel Surcharge Waiver on Credit Cards: What Is It and How Does It Work?`,
  },
  {
    id: `How to Activate Credit Card Online & Offline: Step by Step Guide`,
    imageLink: `https://www.getonecard.app/images/blog/how_to_activate_your_credit_card.png`,
    date: `Nov 15, 2023`,
    query: `How to Activate Credit Card Online & Offline: Step by Step Guide`,
  },
  {
    id: `How to Check Credit Card Balance`,
    imageLink: `https://www.getonecard.app/images/blog/checking_credit_card_balance.png`,
    date: `Nov 15, 2023`,
    query: `How to Check Credit Card Balance`,
  },
  {
    id: `Choose the Best Credit Card in India`,
    imageLink: `https://www.getonecard.app/images/blog/best_credit_card.png`,
    date: `Jul 06, 2023`,
    query: `Choose the Best Credit Card in India`,
  },
  {
    id: `What Credit Card EMI & How Does It Work?`,
    imageLink: `https://www.getonecard.app/images/blog/credit-card-emi.png`,
    date: `Jul 06, 2023`,
    query: `What Credit Card EMI & How Does It Work?`,
  },
  {
    id: `Things to Know Before Getting Your First Credit Card`,
    imageLink: `https://www.getonecard.app/images/blog/first-credit-card.png`,
    date: `Jul 06, 2023`,
    query: `Things to Know Before Getting Your First Credit Card`,
  },
  {
    id: `Credit Card Loan - Apply for Loan Against Credit Card`,
    imageLink: `https://www.getonecard.app/images/blog/Loan_on_credit_card.png`,
    date: `Jun 30, 2023`,
    query: `Credit Card Loan - Apply for Loan Against Credit Card`,
  },
  {
    id: `How to Pay a Credit Card Bill With Another Credit Card?`,
    imageLink: `https://www.getonecard.app/images/blog/credit-bill-with-another-credit-card.png`,
    date: `Jun 30, 2023`,
    query: `How to Pay a Credit Card Bill With Another Credit Card?`,
  },
  {
    id: `How Will the New TCS Impact Your Credit Card Spends`,
    imageLink: `https://www.getonecard.app/images/blog/tcs_charges_on_credit_card_spends.png`,
    date: `Jun 23, 2023`,
    query: `How Will the New TCS Impact Your Credit Card Spends`,
  },
  {
    id: `Credit Card Cash Withdrawal - Charges, Pros and Cons`,
    imageLink: `https://www.getonecard.app/images/blog/CreditCardCashWithdrawalCharges.png`,
    date: `Jun 14, 2023`,
    query: `Credit Card Cash Withdrawal - Charges, Pros and Cons`,
  },
  {
    id: `Fuel Credit Card - Apply for Best Fuel Credit Card Online`,
    imageLink: `https://www.getonecard.app/images/blog/Save_Money_With_Fuel_Credit_Cards.png`,
    date: `Jun 14, 2023`,
    query: `Fuel Credit Card - Apply for Best Fuel Credit Card Online`,
  },
  {
    id: `How to Get Credit Card Without Income Proof`,
    imageLink: `https://www.getonecard.app/images/blog/CreditCardWithoutIncomeProof.png`,
    date: `Jun 14, 2023`,
    query: `How to Get Credit Card Without Income Proof`,
  },
  {
    id: `How to Transfer Money from a Credit Card to a Bank Account?`,
    imageLink: `https://www.getonecard.app/images/blog/Credit_CardtoBankTransfer.png`,
    date: `Jun 14, 2023`,
    query: `How to Transfer Money from a Credit Card to a Bank Account?`,
  },
  {
    id: `Contactless Credit Card - How Does Contactless Payment Work?`,
    imageLink: `https://www.getonecard.app/images/blog/contactlessCreditCards.png`,
    date: `May 30, 2023`,
    query: `Contactless Credit Card - How Does Contactless Payment Work?`,
  },
  {
    id: `Difference Between Credit Card and Debit Card - Pros & Cons`,
    imageLink: `https://www.getonecard.app/images/blog/debitCardVsCreditCard.png`,
    date: `May 30, 2023`,
    query: `Difference Between Credit Card and Debit Card - Pros & Cons`,
  },
  {
    id: `Reasons Why Your Credit Card Application May Get Rejected?`,
    imageLink: `https://www.getonecard.app/images/blog/Reasons_for_Credit_Card_Application_Getting_Rejected.png`,
    date: `May 30, 2023`,
    query: `Reasons Why Your Credit Card Application May Get Rejected?`,
  },
  {
    id: `What is Minimum CIBIL Score Required for Credit Card`,
    imageLink: `https://www.getonecard.app/images/blog/minimumCibilScore.png`,
    date: `May 30, 2023`,
    query: `What is Minimum CIBIL Score Required for Credit Card`,
  },
  {
    id: `How To Generate Or Change Credit Card Pin`,
    imageLink: `https://www.getonecard.app/images/blog/creditcard_pin.png`,
    date: `May 25, 2023`,
    query: `How To Generate Or Change Credit Card Pin`,
  },
  {
    id: `Credit Card CVV Number - What is CVV code and How to Secure it`,
    imageLink: `https://www.getonecard.app/images/blog/cvvblog.png`,
    date: `May 18, 2023`,
    query: `Credit Card CVV Number - What is CVV code and How to Secure it`,
  },
  {
    id: `Secured vs. Unsecured Credit Card: What Are the Differences?`,
    imageLink: `https://www.getonecard.app/images/blog/SecuredVsUnsecuredNew.png`,
    date: `May 17, 2023`,
    query: `Secured vs. Unsecured Credit Card: What Are the Differences?`,
  },
  {
    id: `What Is Credit Card Balance Transfer and How Does It Work?`,
    imageLink: `https://www.getonecard.app/images/blog/credit-card-balance-transfer.png`,
    date: `May 17, 2023`,
    query: `What Is Credit Card Balance Transfer and How Does It Work?`,
  },
  {
    id: `Secured Credit Card: What is It and How to Apply It?`,
    imageLink: `https://www.getonecard.app/images/blog/SecuredCreditCard.png`,
    date: `Apr 18, 2023`,
    query: `Secured Credit Card: What is It and How to Apply It?`,
  },
  {
    id: `5 Ways to Make The Most of Your Credit Card`,
    imageLink: `https://www.getonecard.app/images/blog/howtomakethemostofyourcreditcard.png`,
    date: `Apr 10, 2023`,
    query: `5 Ways to Make The Most of Your Credit Card`,
  },
  {
    id: `Credit Card Getting Declined? How To Avoid It?`,
    imageLink: `https://www.getonecard.app/images/blog/CreditCardGettingDeclinedHereHowToAvoidIt.png`,
    date: `Mar 27, 2023`,
    query: `Credit Card Getting Declined? How To Avoid It?`,
  },
  {
    id: `How To Get a Higher Credit Card Limit?`,
    imageLink: `https://www.getonecard.app/images/blog/OC_Experttipsongettingahighercreditlimit_BlogCreatives.png`,
    date: `Mar 23, 2023`,
    query: `How To Get a Higher Credit Card Limit?`,
  },
  {
    id: `How to Increase Your Credit Card Limit?`,
    imageLink: `https://www.getonecard.app/images/blog/Whodecidesmycreditcardlimit.png`,
    date: `Mar 02, 2023`,
    query: `How to Increase Your Credit Card Limit?`,
  },
  {
    id: `5 Good Credit Card Habits`,
    imageLink: `https://www.getonecard.app/images/blog/Bestcreditcardhabitstofollow.png`,
    date: `Feb 22, 2023`,
    query: `5 Good Credit Card Habits`,
  },
  {
    id: `Tax Deductions on Insurance - Know About 80C & 80D Tax Deductions`,
    imageLink: `https://www.getonecard.app/images/blog/Tax_benefits_on_your_premiums.png`,
    date: `Jan 17, 2023`,
    query: `Tax Deductions on Insurance - Know About 80C & 80D Tax Deductions`,
  },
  {
    id: `Credit Card Defaulters - How to Get Loans From Other Banks?`,
    imageLink: `https://www.getonecard.app/images/blog/OC_Applying_for_a_loan_as_a_defaulter_Blog%20Creatives.png`,
    date: `Dec 30, 2022`,
    query: `Credit Card Defaulters - How to Get Loans From Other Banks?`,
  },
  {
    id: `Insurance Types & Benefits: Power of Insurance & Credit Cards Together`,
    imageLink: `https://www.getonecard.app/images/blog/Power_of_Insurance_Credit_Cards.png`,
    date: `Dec 15, 2022`,
    query: `Insurance Types & Benefits: Power of Insurance & Credit Cards Together`,
  },
  {
    id: `Credit Card Against FD - Apply for Credit Card on FD`,
    imageLink: `https://www.getonecard.app/images/blog/The_credit_score_paradox.png`,
    date: `Dec 15, 2022`,
    query: `Credit Card Against FD - Apply for Credit Card on FD`,
  },
  {
    id: `5 things about credit cards you have got all wrong`,
    imageLink: `https://www.getonecard.app/images/blog/Creditcardmythsdebunked.png`,
    date: `Dec 01, 2022`,
    query: `5 things about credit cards you have got all wrong`,
  },
  {
    id: `Pay Rent with Credit Card Online | OneCard's My Rent`,
    imageLink: `https://www.getonecard.app/images/blog/Missedacreditcardpayment.png`,
    date: `Nov 14, 2022`,
    query: `Pay Rent with Credit Card Online | OneCard's My Rent`,
  },
  {
    id: `Debt Trap - What Is It and How to Avoid It?`,
    imageLink: `https://www.getonecard.app/images/blog/blog-avoid-debt-trap.png`,
    date: `Dec 29, 2021`,
    query: `Debt Trap - What Is It and How to Avoid It?`,
  },
  {
    id: `Do EMIs and BNPL Affect Your Credit Score?`,
    imageLink: `https://www.getonecard.app/images/blog/blog-emi-bnpl-affect-credit-score.png`,
    date: `Dec 20, 2021`,
    query: `Do EMIs and BNPL Affect Your Credit Score?`,
  },
];
